version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    container_name: drone-managment
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
    - "8000:5000"
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: drone-managment-db
    environment:
            SA_PASSWORD: "S3cur3P@ssW0rd!"
            ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"